CC=g++
O=-O3
ROOT=../../../../
INCLUDES=$(ROOT)rubik/*.cpp $(ROOT)rubik/auxiliares/*.cpp $(ROOT)rubik/scores/*.cpp $(ROOT)rubik/scores/basic-score/*.cpp

all:
	$(CC) tuning.cpp $(O) $(INCLUDES) -fopenmp -o tuning.out